version: '3'

services:
  asa_server:
    tty: true
    container_name: asa_server
    build:
      context: .
    env_file:
      - .env
    volumes:
      - shooter_game:/opt/arkserver
      - steam_data:/opt/steamcmd
    ports:
      # Port for connections from ARK game client
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 16g
    memswap_limit: 16g

volumes:
    shooter_game:
    steam_data: