version: '3'

services:
  asa_server:
    tty: true
    container_name: asa_server
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    volumes:
      - shooter_game:/opt/arkserver
      - steam_data:/opt/steamcmd
    ports:
      # Port for connections from ARK game client
      - "${SERVER_PORT}:${SERVER_PORT}/udp"
      #uncomment if you want to expose the RCON Port
      #- "${RCON_PORT}:${RCON_PORT}/tcp"
    networks:
      - default
    # Increase default grace period to ensure clean shutdown
    stop_grace_period: 45s
    deploy:
      resources:
        limits:
          memory: 16g
    # Comment to enable swap
    memswap_limit: 16g

volumes:
    shooter_game:
    steam_data: